export type NoteName = 'C' | 'D' | 'E' | 'F' | 'G' | 'A' | 'B';
export type Octave = 3 | 4;
export type Note = { name: NoteName; octave: Octave; isSharp?: boolean; isFlat?: boolean };

export interface Lesson {
  id: string;
  title: string;
  subtitle: string;
  description: string;
  xp: number;
  concept: string;
  notes: Note[];
  sheetNotes: string[]; // notes for the mini-song in this lesson
  order: number;
}

export const lessons: Lesson[] = [
  {
    id: '1',
    title: 'Middle C',
    subtitle: 'Your first note',
    description: 'Learn to find and play Middle C — the foundation of piano music.',
    xp: 50,
    concept: 'Middle C is the white key to the left of the two black keys, near the center of the piano.',
    notes: [{ name: 'C', octave: 4 }],
    sheetNotes: ['C4', 'C4', 'C4', 'C4'],
    order: 1,
  },
  {
    id: '2',
    title: 'D & E',
    subtitle: 'Stepping up',
    description: 'Add D and E — the next two white keys after C.',
    xp: 50,
    concept: 'D is right next to C. E comes after D. These three notes form the beginning of the C major scale.',
    notes: [
      { name: 'D', octave: 4 },
      { name: 'E', octave: 4 },
    ],
    sheetNotes: ['C4', 'D4', 'E4', 'D4', 'C4'],
    order: 2,
  },
  {
    id: '3',
    title: 'F & G',
    subtitle: 'Reaching higher',
    description: 'Learn F and G to complete your first five notes.',
    xp: 50,
    concept: 'F is to the left of the three black keys. G comes after F. You now know C-D-E-F-G!',
    notes: [
      { name: 'F', octave: 4 },
      { name: 'G', octave: 4 },
    ],
    sheetNotes: ['C4', 'D4', 'E4', 'F4', 'G4', 'F4', 'E4', 'D4', 'C4'],
    order: 3,
  },
  {
    id: '4',
    title: 'A & B',
    subtitle: 'Completing the octave',
    description: 'Learn A and B to finish all the white keys in one octave.',
    xp: 60,
    concept: 'A is after G, and B is the last white key before we reach C again. You now know the entire C major scale!',
    notes: [
      { name: 'A', octave: 4 },
      { name: 'B', octave: 4 },
    ],
    sheetNotes: ['C4', 'D4', 'E4', 'F4', 'G4', 'A4', 'B4', 'C5'],
    order: 4,
  },
  {
    id: '5',
    title: 'Your First Song',
    subtitle: 'Ode to Joy',
    description: 'Play Beethoven\'s Ode to Joy using the notes you\'ve learned.',
    xp: 100,
    concept: 'Congratulations! Use all the white keys from C to G to play this classic melody.',
    notes: [
      { name: 'E', octave: 4 },
      { name: 'F', octave: 4 },
      { name: 'G', octave: 4 },
    ],
    sheetNotes: ['E4', 'E4', 'F4', 'G4', 'G4', 'F4', 'E4', 'D4', 'C4', 'C4', 'D4', 'E4', 'E4', 'D4', 'D4'],
    order: 5,
  },
  {
    id: '6',
    title: 'Left Hand C',
    subtitle: 'Bass notes',
    description: 'Introduce your left hand with Middle C one octave down.',
    xp: 60,
    concept: 'Your left hand plays lower notes. Find C one octave below Middle C — same pattern, just lower.',
    notes: [{ name: 'C', octave: 3 }],
    sheetNotes: ['C3', 'C4', 'C3', 'C4'],
    order: 6,
  },
  {
    id: '7',
    title: 'Two-Hand C Major',
    subtitle: 'Both hands together',
    description: 'Play the C major scale with both hands simultaneously.',
    xp: 80,
    concept: 'Try playing the same notes with both hands. This builds coordination between left and right hands.',
    notes: [
      { name: 'C', octave: 4 },
      { name: 'D', octave: 4 },
      { name: 'E', octave: 4 },
    ],
    sheetNotes: ['C4', 'D4', 'E4', 'F4', 'G4'],
    order: 7,
  },
  {
    id: '8',
    title: 'Twinkle Twinkle',
    subtitle: 'Classic melody',
    description: 'Play Twinkle Twinkle Little Star — a timeless beginner piece.',
    xp: 120,
    concept: 'This melody uses C, D, E, F, G, and A. Notice how the melody moves in steps and small skips.',
    notes: [
      { name: 'C', octave: 4 },
      { name: 'D', octave: 4 },
      { name: 'E', octave: 4 },
      { name: 'F', octave: 4 },
      { name: 'G', octave: 4 },
      { name: 'A', octave: 4 },
    ],
    sheetNotes: ['C4', 'C4', 'G4', 'G4', 'A4', 'A4', 'G4', 'F4', 'F4', 'E4', 'E4', 'D4', 'D4', 'C4'],
    order: 8,
  },
  {
    id: '9',
    title: 'Sharps & Flats',
    subtitle: 'The black keys',
    description: 'Discover sharps and flats — the black keys on the piano.',
    xp: 70,
    concept: 'The black key to the right of a white key is its sharp (♯). The black key to the left is its flat (♭). C♯ and D♭ are the same key!',
    notes: [
      { name: 'C', octave: 4, isSharp: true },
      { name: 'D', octave: 4, isSharp: true },
    ],
    sheetNotes: ['C4', 'C#4', 'D4', 'D#4', 'E4'],
    order: 9,
  },
  {
    id: '10',
    title: 'Mary Had a Little Lamb',
    subtitle: 'With sharps',
    description: 'A nursery rhyme that uses both white and black keys.',
    xp: 150,
    concept: 'This song uses E, D, C and introduces F♯. Notice how F♯ creates a brighter, lifted feeling.',
    notes: [
      { name: 'E', octave: 4 },
      { name: 'D', octave: 4 },
      { name: 'C', octave: 4 },
      { name: 'F', octave: 4, isSharp: true },
    ],
    sheetNotes: ['E4', 'D4', 'C4', 'D4', 'E4', 'E4', 'E4', 'D4', 'D4', 'D4', 'E4', 'G4', 'G4', 'E4', 'D4', 'C4', 'D4', 'E4', 'E4', 'E4', 'E4', 'D4', 'D4', 'E4', 'D4', 'C4'],
    order: 10,
  },
  {
    id: '11',
    title: 'D♭ & E♭',
    subtitle: 'Flats on the two-group',
    description: 'Discover D♭ and E♭ — the flat names for the black keys in the two-black-key group.',
    xp: 60,
    concept: 'A flat (♭) means "play the black key to the left." D♭ is the black key left of D. E♭ is left of E. These are the same keys as C♯ and D♯ — every black key has two names!',
    notes: [
      { name: 'D', octave: 4, isFlat: true },
      { name: 'E', octave: 4, isFlat: true },
    ],
    sheetNotes: ['D4', 'Db4', 'D4', 'E4', 'Eb4', 'E4'],
    order: 11,
  },
  {
    id: '12',
    title: 'G♭, A♭ & B♭',
    subtitle: 'Flats on the three-group',
    description: 'Learn G♭, A♭, and B♭ — the flat names for the three-black-key group.',
    xp: 60,
    concept: 'G♭ is left of G, A♭ is left of A, B♭ is left of B. B♭ is especially common — you\'ll hear it in countless songs! Together with D♭ and E♭, you now know all five flats.',
    notes: [
      { name: 'G', octave: 4, isFlat: true },
      { name: 'A', octave: 4, isFlat: true },
      { name: 'B', octave: 4, isFlat: true },
    ],
    sheetNotes: ['G4', 'Gb4', 'G4', 'A4', 'Ab4', 'A4', 'Bb4', 'A4'],
    order: 12,
  },
  {
    id: '13',
    title: 'Two Names, One Key',
    subtitle: 'Enharmonics review',
    description: 'Every black key has two names — a sharp name and a flat name. Master them all.',
    xp: 70,
    concept: 'C♯ = D♭, D♯ = E♭, F♯ = G♭, G♯ = A♭, A♯ = B♭. Same keys, different names. Musicians choose based on the key they\'re playing in — but for now, you know both!',
    notes: [
      { name: 'C', octave: 4, isSharp: true },
      { name: 'D', octave: 4, isFlat: true },
      { name: 'D', octave: 4, isSharp: true },
      { name: 'E', octave: 4, isFlat: true },
      { name: 'F', octave: 4, isSharp: true },
      { name: 'G', octave: 4, isFlat: true },
      { name: 'G', octave: 4, isSharp: true },
      { name: 'A', octave: 4, isFlat: true },
      { name: 'A', octave: 4, isSharp: true },
      { name: 'B', octave: 4, isFlat: true },
    ],
    sheetNotes: ['C4', 'C#4', 'Db4', 'D4', 'D#4', 'Eb4', 'E4', 'F4', 'F#4', 'Gb4', 'G4', 'G#4', 'Ab4', 'A4', 'A#4', 'Bb4', 'B4', 'C5'],
    order: 13,
  },
  {
    id: '14',
    title: 'Song with Flats',
    subtitle: 'Putting it together',
    description: 'Play a melody that uses white keys and flats — a real musical workout.',
    xp: 120,
    concept: 'Put your flat knowledge to use! This melody uses B♭ alongside white keys. Notice how B♭ adds a different color to the sound — a little bluesy, a little soulful.',
    notes: [
      { name: 'B', octave: 4, isFlat: true },
      { name: 'C', octave: 4 },
      { name: 'D', octave: 4 },
      { name: 'F', octave: 4 },
      { name: 'G', octave: 4 },
    ],
    sheetNotes: ['F4', 'G4', 'A4', 'Bb4', 'A4', 'G4', 'F4', 'D4', 'F4', 'G4', 'A4', 'C5', 'Bb4', 'A4', 'G4', 'F4'],
    order: 14,
  },
  {
    id: '15',
    title: 'Left Hand Steps',
    subtitle: 'Walking bass',
    description: 'Teach your left hand to walk through bass notes — the foundation of piano music.',
    xp: 60,
    concept: 'Your left hand can play melodies too! These lower notes — C, D, E, F, G one octave down — are the bass foundations. Walking between them creates a sense of movement.',
    notes: [
      { name: 'C', octave: 3 },
      { name: 'D', octave: 3 },
      { name: 'E', octave: 3 },
      { name: 'F', octave: 3 },
      { name: 'G', octave: 3 },
    ],
    sheetNotes: ['C3', 'D3', 'E3', 'F3', 'G3', 'F3', 'E3', 'D3', 'C3'],
    order: 15,
  },
  {
    id: '16',
    title: 'Hands Apart',
    subtitle: 'Two different parts',
    description: 'Right hand plays melody, left hand plays bass — two parts moving independently.',
    xp: 80,
    concept: 'This is hand independence: the right hand plays a melody in octave 4 while the left hand jumps between C3 and G3 as bass notes. They move at different times — that\'s the challenge!',
    notes: [
      { name: 'C', octave: 3 },
      { name: 'G', octave: 3 },
      { name: 'C', octave: 4 },
      { name: 'D', octave: 4 },
      { name: 'E', octave: 4 },
    ],
    sheetNotes: ['C3', 'C4', 'D4', 'E4', 'G3', 'E4', 'D4', 'C4'],
    order: 16,
  },
  {
    id: '17',
    title: 'Left Hand Melody',
    subtitle: 'Bass takes the tune',
    description: 'Your left hand gets the spotlight — play a complete melody in the bass register.',
    xp: 80,
    concept: 'Surprise — your left hand can carry the tune! This simple descending melody lives entirely in octave 3. Playing melodies with the left hand builds dexterity and confidence.',
    notes: [
      { name: 'C', octave: 3 },
      { name: 'D', octave: 3 },
      { name: 'E', octave: 3 },
    ],
    sheetNotes: ['E3', 'D3', 'C3', 'D3', 'E3', 'E3', 'E3', 'D3', 'D3', 'E3', 'D3', 'C3'],
    order: 17,
  },
  {
    id: '18',
    title: 'Two-Hand Duet',
    subtitle: 'Putting it all together',
    description: 'Combine independent left and right hand parts into one beautiful piece.',
    xp: 120,
    concept: 'Everything comes together! The right hand plays a soaring melody while the left hand provides a steady bass foundation. Two independent voices, one song — this is what piano playing is all about.',
    notes: [
      { name: 'C', octave: 3 },
      { name: 'G', octave: 3 },
      { name: 'C', octave: 4 },
      { name: 'D', octave: 4 },
      { name: 'E', octave: 4 },
      { name: 'F', octave: 4 },
      { name: 'G', octave: 4 },
    ],
    sheetNotes: ['C3', 'C4', 'D4', 'E4', 'G3', 'F4', 'E4', 'D4', 'C3', 'E4', 'F4', 'G4', 'G3', 'F4', 'E4', 'C4'],
    order: 18,
  },
  {
    id: '19',
    title: 'What Is a Chord?',
    subtitle: 'The C major triad',
    description: 'Discover chords — multiple notes played together that create harmony.',
    xp: 60,
    concept: 'A chord is 3 or more notes played together. The C major chord uses C, E, and G — the 1st, 3rd, and 5th notes of the C major scale. Play them one at a time, then imagine them ringing together!',
    notes: [
      { name: 'C', octave: 4 },
      { name: 'E', octave: 4 },
      { name: 'G', octave: 4 },
    ],
    sheetNotes: ['C4', 'E4', 'G4', 'E4', 'C4', 'C4', 'E4', 'G4', 'E4', 'C4'],
    order: 19,
  },
  {
    id: '20',
    title: 'F & G Chords',
    subtitle: 'The other two pillars',
    description: 'Learn F major and G major — the other two essential chords in C major.',
    xp: 70,
    concept: 'F major is F-A-C. G major is G-B-D. Together with C major (C-E-G), these three chords — called I, IV, and V — can accompany thousands of songs!',
    notes: [
      { name: 'F', octave: 4 },
      { name: 'A', octave: 4 },
      { name: 'G', octave: 4 },
      { name: 'B', octave: 4 },
    ],
    sheetNotes: ['F4', 'A4', 'C5', 'A4', 'F4', 'G4', 'B4', 'D5', 'B4', 'G4'],
    order: 20,
  },
  {
    id: '21',
    title: 'Chord Progressions',
    subtitle: 'Chords in motion',
    description: 'String chords together into progressions — the backbone of every song.',
    xp: 80,
    concept: 'A chord progression is a sequence of chords. The most common progression in Western music is C → F → G → C. The left hand plays the root note while the right hand plays the chord tones — try alternating between them!',
    notes: [
      { name: 'C', octave: 3 },
      { name: 'F', octave: 3 },
      { name: 'G', octave: 3 },
      { name: 'C', octave: 4 },
      { name: 'E', octave: 4 },
      { name: 'G', octave: 4 },
    ],
    sheetNotes: ['C3', 'C4', 'E4', 'G4', 'F3', 'F4', 'A4', 'C5', 'G3', 'G4', 'B4', 'D5', 'C3', 'C4', 'E4', 'G4'],
    order: 21,
  },
  {
    id: '22',
    title: 'Song with Chords',
    subtitle: 'Harmony in action',
    description: 'Play a song that uses chord accompaniment — melody and harmony together.',
    xp: 130,
    concept: 'This is what piano playing sounds like! The left hand provides the chord roots (C, F, G) while the right hand plays a melody built from chord tones. This is how singer-songwriters, pop pianists, and classical composers all think about music.',
    notes: [
      { name: 'C', octave: 3 },
      { name: 'F', octave: 3 },
      { name: 'G', octave: 3 },
      { name: 'C', octave: 4 },
      { name: 'D', octave: 4 },
      { name: 'E', octave: 4 },
      { name: 'F', octave: 4 },
      { name: 'G', octave: 4 },
    ],
    sheetNotes: ['C3', 'E4', 'G4', 'C5', 'G4', 'E4', 'F3', 'F4', 'A4', 'C5', 'A4', 'F4', 'C3', 'C4', 'E4', 'G4', 'G3', 'D4', 'G4', 'B4', 'G4', 'D4', 'C3', 'C4', 'E4', 'G4', 'C5'],
    order: 22,
  },
];
